<?php

return [
    'fields'=>
        [
            'seo_title',
            'seo_description',
            'seo_keywords',
            'seo_text',
        ],
    'owners'=>
        [
            'slider',
            'contacts',
            'about',
            'pay',
            'services',
            'sale',
            'guarantee',
            'components',
            'components_categories',
            'components_list',
            'windows_price',
            'balcony_price',
            'products',
            'products_list_1',
            'products_list_2',
            'other_products_list',
            'calculator',
        ]
];
